# Generated by Django 2.0.1 on 2018-01-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.TextField(help_text='Separar tags por vírgula.'),
        ),
    ]
